vrchat-community/creator-docs

Docs/src/theme/NotFound.js
=> Sync from upstream repo 06/14/2023 19:44:46

Docs/docs/avatars/expression-menu-and-controls.md, Docs/docs/worlds/components/vrc_spatialaudiosource.md, Docs/docs/worlds/udon/players/player-collisions.md, Docs/docusaurus.config.js
=> Sync from upstream repo 06/20/2023 20:29:00

Docs/docs/avatars/animator-parameters.md, Docs/docs/platforms/android/quest-content-limitations.md, Docs/releases/release-3.2.2.md
=> Sync from upstream repo 06/29/2023 20:55:25

Docs/docs/worlds/udon/image-loading.md
=> rename OnImageLoadFailure to OnImageLoadError

Docs/docs/avatars/avatar-performance-ranking-system.md, Docs/docs/avatars/state-behaviors.md, Docs/docs/worlds/components/vrc_spatialaudiosource.md, Docs/docs/worlds/layers.md, Docs/docs/worlds/udon/graph/event-nodes.md, Docs/docs/worlds/udon/players/getting-players.md, Docs/docs/worlds/udon/players/index.md, Docs/docs/worlds/udon/players/player-audio.md, Docs/docs/worlds/udon/players/player-forces.md, Docs/docs/worlds/udon/players/player-positions.md, Docs/docs/worlds/udon/string-loading.md, Docs/docusaurus.config.js
=> Sync from upstream repo 07/19/2023 23:20:39

Docs/docs/worlds/components/vrc_scenedescriptor.md, Docs/docs/worlds/layers.md, Docs/docs/worlds/udon/avatar-events.md, Docs/docs/worlds/udon/players/player-avatar-scaling.md, Docs/releases/release-3.2.1.md
=> Sync from upstream repo 07/31/2023 23:32:47

Docs/docs/avatars/whitelisted-avatar-components.md, Docs/docs/worlds/components/index.md, Docs/docs/worlds/index.md, Docs/docs/worlds/supported-assets.md, Docs/docs/worlds/udon/animation-events.md, Docs/docs/worlds/udon/udon-moderation-tool-guidelines.md, Docs/docs/worlds/udon/video-players/index.md, Docs/docs/worlds/udon/video-players/www-whitelist.md, Docs/docs/worlds/whitelisted-world-components.md, Docs/releases/release-3.2.0.md
Replaced "whitelist" and "blacklist" with "allowlist" and "banlist"/"blocklist" as appropriate.
Updated allowed service URLs. I grabbed the latest VRChat API config, removed the non-public-services, and updated the table.
=> Wording changes

Docs/docs/platforms/android/android-best-practices.md, Docs/docs/worlds/udon/players/index.md, Docs/docusaurus.config.js
=> Sync from upstream repo 08/05/2023 02:32:34

Docs/docs/worlds/udon/players/index.md
=> Sync from upstream repo 08/11/2023 22:12:06

Docs/docs/worlds/udon/players/index.md, Docs/releases/release-3.2.3.md
=> Sync from upstream repo 08/18/2023 16:34:58

Docs/docs/sdk/public-sdk-api.md, Docs/docs/worlds/udon/players/player-positions.md, Docs/releases/release-3.3.0.md
=> Sync from upstream repo 08/28/2023 19:08:53

Docs/docs/worlds/submitting-a-world-to-be-made-public.md
=> Sync from upstream repo 08/28/2023 23:26:00

Docs/docs/avatars/creating-your-first-avatar.md
=> Sync from upstream repo 08/29/2023 17:45:36

Docs/.frontmatter/database/taxonomyDb.json, Docs/docs/platforms/android/android-best-practices.md, Docs/docs/sdk/current-unity-version.md, Docs/docs/sdk/public-sdk-api.md, Docs/docs/worlds/components/vrc_scenedescriptor.md, Docs/docs/worlds/components/vrc_station.md, Docs/docs/worlds/udon/avatar-events.md, Docs/docs/worlds/udon/image-loading.md, Docs/docs/worlds/udon/video-players/index.md, Docs/frontmatter.json
=> Sync from upstream repo 09/01/2023 16:35:37

Docs/releases/release-3.4.0.md
=> Sync from upstream repo 09/19/2023 22:17:54

Docs/releases/release-3.4.0.md
=> Sync from upstream repo 09/28/2023 21:28:44

Docs/releases/release-3.4.0.md
=> Sync from upstream repo 10/05/2023 18:34:06

Docs/docs/worlds/udon/data-containers/vrcjson.md, Docs/docs/worlds/udon/image-loading.md, Docs/releases/release-3.4.0.md, Docs/releases/release-3.4.1.md
=> Sync from upstream repo 10/18/2023 19:24:54

Docs/docs/worlds/udon/data-containers/vrcjson.md
=> Sync from upstream repo 10/18/2023 23:04:53

Docs/docs/avatars/avatar-dynamics/index.md
Adjusted the path to reflect the latest SDK version
=> Correction in avatars/avatar-dynamics

Docs/docs/avatars/index.md
- Changing LookUp/LookDown variables and simplified the -none- description
=> Corrections in avatars\index.md

Docs/docs/avatars/animator-parameters.md, Docs/docs/avatars/avatar-dynamics/index.md, Docs/docs/avatars/creating-your-first-avatar.md, Docs/docs/avatars/index.md, Docs/docs/avatars/whitelisted-avatar-components.md, Docs/docs/worlds/udon/index.md
Changes Files:
- Docs/docs/avatars/animator-parameters.md
=> Sync from upstream repo 11/28/2023 22:06:43

Docs/docs/avatars/avatar-dynamics/contacts.md
Unordered list have been added for better readability
=> Improved Formating of Contacts.md

Docs/releases/release-3.5.0.md
Changes Files:
- Docs/docs/avatars/avatar-optimizing-tips.md
- Docs/docs/platforms/android/android-best-practices.md
- Docs/docs/platforms/android/quest-content-limitations.md
- Docs/docs/sdk/current-unity-version.md
- Docs/docs/sdk/index.md
- Docs/docs/sdk/migrating-to-a-newer-minor-unity-version.md
- Docs/docs/sdk/sdk-troubleshooting.md
- Docs/docs/sdk/updating-the-sdk.md
- Docs/docs/sdk/upgrade/current-unity-version.md
- Docs/docs/sdk/upgrade/index.md
- Docs/docs/sdk/upgrade/migrating-to-a-newer-minor-unity-version.md
- Docs/docs/sdk/upgrade/unity-2022.md
- Docs/docs/sdk/upgrade/worlds-and-avatars-in-2022.md
- Docs/docs/worlds/components/vrc_portalmarker.md
- Docs/docs/worlds/udon/getting-started-with-udon.md
- Docs/docs/worlds/udon/graph/event-nodes.md
- Docs/releases/release-3.4.2.md …
=> Sync from upstream repo 12/08/2023 23:54:10

Docs/docs/avatars/animator-parameters.md, Docs/docs/avatars/avatar-dynamics/index.md, Docs/docs/avatars/creating-your-first-avatar.md, Docs/docs/avatars/index.md, Docs/docs/sdk/public-sdk-api.md, Docs/docs/sdk/upgrade/current-unity-version.md, Docs/docs/sdk/upgrade/unity-2022.md
Changes Files:
- Docs/releases/release-3.5.0.md
=> Sync from upstream repo 12/14/2023 23:43:23

Docs/docs/avatars/animator-parameters.md, Docs/docs/avatars/avatar-performance-ranking-system.md, Docs/docs/sdk/index.md, Docs/docs/sdk/upgrade/current-unity-version.md, Docs/docs/worlds/examples/udon-example-scene/index.md, Docs/docs/worlds/examples/udon-example-scene/player-mod-setter.md, Docs/docs/worlds/examples/udon-example-scene/world-audio-settings.md, Docs/docs/worlds/udon/graph/event-nodes.md, Docs/docs/worlds/udon/graph/special-nodes.md, Docs/docs/worlds/udon/players/index.md
Changes Files:
- Docs/docs/avatars/animator-parameters.md
- Docs/docs/avatars/avatar-dynamics/index.md
- Docs/docs/avatars/creating-your-first-avatar.md
- Docs/docs/avatars/index.md
- Docs/docs/sdk/public-sdk-api.md
- Docs/docs/sdk/upgrade/current-unity-version.md
- Docs/docs/sdk/upgrade/unity-2022.md
=> Sync from upstream repo 01/02/2024 23:33:56

Docs/docs/avatars/index.md
=> fix description in avatar Simulated eye movement doc #105

Docs/docs/sdk/upgrade/current-unity-version.md
Changes Files:
- Docs/docs/avatars/index.md
=> Sync from upstream repo 01/16/2024 20:43:23

Docs/docs/worlds/vrc-graphics/asyncgpureadback.md
when it says 3 steps but the list display 4 steps
=> Replacing the number of step

Docs/docs/sdk/detecting-vrcsdk.md
Closes #50
This adds documentation about legacy scripting symbols based on my understanding.
=> Add about detecting vrcsdk and legacy scripting defines

Docs/releases/release-3.5.1.md
=> Sync from upstream repo 02/21/2024 01:13:38

Docs/docs/worlds/udon/players/index.md
=> remove outdated infomation in Player API doc

Docs/docs/worlds/udon/video-players/index.md
=> remove outdated infomation in Video Player docs

Docs/docs/worlds/udon/networking/index.md, Docs/docs/worlds/udon/networking/network-components.md, Docs/docs/worlds/udon/players/index.md, Docs/docs/worlds/udon/world-debug-views.md
=> Sync from upstream repo 03/13/2024 21:55:48

Docs/docs/worlds/udon/vm-and-assembly/index.md
The Udon VM and Udon Assembly are mentioned but not documented.
Adds that documentation.
=> Add a page on the Udon VM and Udon Assembly.

Docs/docs/avatars/creating-your-first-avatar.md, Docs/src/components/FeedbackButton.js
=> Sync from upstream repo 03/28/2024 01:21:43

Docs/docs/avatars/state-behaviors.md, Docs/docs/worlds/components/vrc_mirrorreflection.md
=> Sync from upstream repo 04/04/2024 23:59:05

Docs/docs/economy/sdk/examples/debug-logging.md, Docs/docs/economy/sdk/examples/floating-overhead.md, Docs/docs/economy/sdk/examples/index.md, Docs/docs/economy/sdk/examples/open-group-page.md, Docs/docs/economy/sdk/examples/product-toggle.md, Docs/docs/economy/sdk/examples/subs-instance.md, Docs/docs/economy/sdk/examples/subs-only.md, Docs/docs/economy/sdk/examples/timed-event.md
=> Sync from upstream repo 04/10/2024 21:17:58

Docs/docs/platforms/android/android-best-practices.md, Docs/docs/worlds/components/vrc_uishape.md
=> Sync from upstream repo 04/24/2024 22:13:43

Docs/docs/platforms/android/android-best-practices.md
=> Sync from upstream repo 05/08/2024 13:27:19

Docs/docs/worlds/components/vrc_uishape.md, Docs/docs/worlds/layers.md, Docs/docs/worlds/udon/external-urls.md, Docs/releases/release-3.5.3.md, Docs/releases/release-3.6.0.md
=> Sync from upstream repo 05/09/2024 17:56:52

Docs/docs/roadmap.md, Docs/docusaurus.config.js
=> Sync from upstream repo 05/14/2024 20:34:30

Docs/docs/avatars/avatar-dynamics/physbones.md
=> add `{parameter}_Squish`

Docs/docs/roadmap.md
=> Sync from upstream repo 06/18/2024 23:30:46

Docs/docs/roadmap.md
=> Sync from upstream repo 06/28/2024 21:39:49

Docs/docs/worlds/udon/input-events.md, Docs/docs/worlds/udon/networking/network-components.md
=> Sync from upstream repo 07/22/2024 22:24:13

Docs/docs/contribute/accessibility.md, Docs/docs/contribute/index.md, Docs/docs/contribute/style.md, Docs/docs/contribute/syntax.md, Docs/src/components/APITable/index.tsx, Docs/src/components/APITable/styles.module.css, Docs/src/components/BrowserWindow/IframeWindow.tsx, Docs/src/components/BrowserWindow/index.tsx, Docs/src/components/BrowserWindow/styles.module.css
=> Sync from upstream repo 07/23/2024 00:58:13

Docs/docs/worlds/udon/ai-navigation.md
=> Sync from upstream repo 07/24/2024 20:31:15

Docs/docs/sdk/index.md
- Moves tip about building quest content above list
- Updates old terms (Oculus → Meta, Plastic SCM → Unity Version Control)
=> Moves tip, updates old terms

Docs/docs/avatars/avatar-size-limits.md, Docs/docs/economy/products/paid-roles.md, Docs/docs/platforms/pc/steamvr-drivers.md
=> Sync from upstream repo 07/31/2024 02:02:25

Docs/docs/worlds/udon/world-debug-views.md
=> Sync from upstream repo 08/12/2024 13:04:07

Docs/releases/release-3.7.1.md
=> Sync from upstream repo 09/20/2024 18:46:50

Docs/docs/economy/faq.md, Docs/docs/economy/getting-started.md, Docs/docs/economy/guidelines.md, Docs/docs/economy/index.md, Docs/docs/economy/payout.md, Docs/docs/economy/products/index.md, Docs/docs/economy/products/paid-roles.md, Docs/docs/economy/products/udon.md, Docs/docs/economy/purchasing-credits.md, Docs/docs/economy/sdk/examples/debug-logging.md, Docs/docs/economy/sdk/examples/floating-overhead.md, Docs/docs/economy/sdk/examples/index.md, Docs/docs/economy/sdk/examples/open-group-page.md, Docs/docs/economy/sdk/examples/product-toggle.md, Docs/docs/economy/sdk/examples/subs-instance.md, Docs/docs/economy/sdk/examples/subs-only.md, Docs/docs/economy/sdk/examples/supporter-list.md, Docs/docs/economy/sdk/examples/timed-event.md, Docs/docs/economy/sdk/getting-started.md, Docs/docs/economy/sdk/index.md, Docs/docs/economy/sdk/testing.md, Docs/docs/economy/sdk/udon-documentation.md, Docs/docs/economy/store.md, Docs/package-lock.json, Docs/package.json, Docs/src/theme/DocCard/index.tsx, Docs/src/theme/DocCard/styles.module.css
=> Sync from upstream repo 09/23/2024 15:02:38

Docs/docs/economy/_ce-how-to-import.mdx, Docs/docs/economy/sdk/examples/debug-logging.md, Docs/docs/economy/sdk/examples/floating-overhead.md, Docs/docs/economy/sdk/examples/open-group-page.md, Docs/docs/economy/sdk/examples/product-toggle.md, Docs/docs/economy/sdk/examples/subs-instance.md, Docs/docs/economy/sdk/examples/subs-only.md, Docs/docs/economy/sdk/examples/supporter-list.md, Docs/docs/economy/sdk/examples/timed-event.md
=> Sync from upstream repo 10/16/2024 21:53:28

Docs/docs/economy/sdk/examples/open-group-page.md, Docs/docs/economy/sdk/examples/open-listing.md
=> Sync from upstream repo 10/17/2024 16:37:28

Docs/docs/roadmap.md
=> Sync from upstream repo 10/21/2024 14:11:37

Docs/docs/getting-started.md, Docs/docs/sdk/example-central.md
=> Sync from upstream repo 11/01/2024 17:32:20

Docs/docs/avatars/animator-parameters.md, Docs/docs/avatars/avatar-dynamics/debugging-avatar-dynamics.md, Docs/releases/release-3.7.3.md
=> Sync from upstream repo 11/05/2024 23:17:56

Docs/docs/worlds/udon/video-players/www-whitelist.md
Updated list to comply with current standard.
(only major services which known well as requested by Fax previously)
*There are some domain change on existing service also so it is better get updated.
=> Update to Trusted URLs list

Docs/docs/avatars/animator-parameters.md, Docs/docs/avatars/avatar-performance-ranking-system.md, Docs/docs/avatars/avatar-size-limits.md, Docs/docs/avatars/state-behaviors.md, Docs/docs/economy/faq.md, Docs/docs/economy/getting-started.md, Docs/docs/economy/listings.md, Docs/docs/economy/payout.md, Docs/docs/economy/sdk/examples/index.md, Docs/docs/economy/sdk/examples/open-group-page.md, Docs/docs/economy/store/index.md, Docs/docs/economy/subscriptions.md, Docs/docs/platforms/iOS/index.md, Docs/docs/sdk/example-central.md, Docs/docs/worlds/components/vrc_spatialaudiosource.md, Docs/docs/worlds/components/vrc_station.md, Docs/docs/worlds/creating-your-first-world.md, Docs/docs/worlds/udon/data-containers/data-dictionaries.md, Docs/docs/worlds/udon/data-containers/index.md, Docs/docs/worlds/udon/index.md, Docs/docs/worlds/udon/networking/index.md, Docs/docs/worlds/udon/networking/network-details.md, Docs/docs/worlds/udon/persistence/index.md, Docs/docs/worlds/udon/persistence/player-data.md, Docs/docs/worlds/udon/persistence/player-object.md, Docs/docs/worlds/udon/players/player-positions.md, Docs/docs/worlds/udon/video-players/www-whitelist.md
=> Sync from upstream repo 01/06/2025 21:35:57

Docs/docs/worlds/udon/udonsharp/performance-tips.md
=> Fixed typo in performance-tips.md

Docs/docs/economy/_sellers-notification.mdx, Docs/docs/economy/sdk/examples/open-listing.md
=> Sync from upstream repo 02/12/2025 10:23:18

Docs/docs/avatars/creating-your-first-avatar.md
added jinxxy and avatown alongside booth and gumroad and fixed a typo
=> Updated creating-your-first-avatar.md with more avatar marketplace names

Docs/releases/release-3.7.6.md
=> Sync from upstream repo 03/05/2025 18:28:01

Docs/docs/worlds/udon/image-loading.md, Docs/docs/worlds/udon/string-loading.md
#209 
Closed by mistake as it seems so let me put it up again.
=> Add missing trusted URL entry for String Loader and Image Loading

Docs/docs/economy/faq.md, Docs/docs/economy/guidelines.md, Docs/docs/economy/index.md, Docs/docs/economy/payout.md, Docs/docs/economy/products/paid-role.md, Docs/docs/economy/store/group-store.md, Docs/docs/economy/store/index.md, Docs/docs/economy/store/world-store.md, Docs/docs/economy/subscriptions.md
=> Sync from upstream repo 04/25/2025 21:31:01

Docs/docs/economy/guidelines.md
=> Sync from upstream repo 05/14/2025 19:53:35

Docs/docs/economy/guidelines.md, Docs/docs/economy/payout.md, Docs/docs/economy/products/avatar.md
=> Sync from upstream repo 05/20/2025 21:06:16

Docs/releases/release-3.8.1.md
=> Sync from upstream repo 05/28/2025 17:03:14

Docs/docs/avatars/avatar-performance-ranking-system.md
Fixes a typo in avatar-performance-ranking-system.md.
=> fix(avatar-performance-ranking-system.md): my -> by

Docs/docs/economy/guidelines.md
=> Sync from upstream repo 09/26/2025 15:45:38
